### ISSUE TITLE
Prevent Price Manipulation

### ISSUE THREAD

**Issue by GauthamN** [KyberNetwork/smart-contracts#1]
How about using a threshold variable that is set by a each Reserve? It would be transparent to all the contributors and they would only contribute on agreement. During SetRate, if the new rate is lower than the old rate multiplied by the threshold variable (0 < thresholdVariable < 1), it results in failure or can call DynamicPriceCheck function which refers to other Reserves for price. This function can be designed like:

          uint matchingBalance = 0;       
          for( uint i = 0 ; i < numReserves ; i++ ) {
            var (rate,expBlock,balance) = reserves[i].getPairInfo(source,dest); 
            /// isClose is a math function that checks if the rates are close to each other       
            if( (expBlock >= block.number) && (balance > 0) && (isClose(rate, newRate) ) ) {
                 matchingBalance +=  balance;
            }
          }
          if( ! reserveBalance <= matchingBalance ) { return false; }

## Why DynamicPriceCheck Works

matchingBalance is basically the total balance of the given pair in all reserves whose rate is similar to the newRate the ReserveManager is trying to set. It basically checks if matchingBalance is higher the balance of the ReserveManager's Reserve which means that there are other Reserves greater of equal in combined value who have already set a similar rate. 

In a very unlikely scenario, It is still possible to manipulate if the ReserveManager sets up another decoy Reserve with balance greater than the original Reserve and sets an unreasonable rate for it before setting rate for the original one. With a high gas price, the ReserveManager can probably peform all three transactions (Setting rate of two reserve and purchase of the assets himself) before someone else capitalises on the unreasonably low exchange rate. This is obviously impractical for high volume exchange pairs but still a valid concern for the low volume ones. So, further enhancements are required.

If the Reserve Manager is the first to set rate after a legitimate drastic rate drop, this wouldn't work and other mechanisms should be used. But it would avoid all smaller reserves having the same pair having to go through the same cumbersome mechanism.

**Comment by yaronvel** [comment]
We have different mechanism in mind.
For example, if the prices of two reserves are close, then we would not necessarily choose the cheapest one, rather just give it higher priority. There will be some fairness mechanism.

In more broader aspect, what you consider is that reserve managers could collaborate in setting prices.
This could be done also out side our contracts, by setting the reserve owner to be a smart contract.
But I am not sure we should encourage it. Though at these point I am also not sure we should prevent it.

**Comment by GauthamN** [comment]
I'd love to know your thoughts on what other mechanisms you are considering for preventing price manipulation by reserve managers. Because explicit permission from contributors in the smart contract when the new rate is below the threshold is the only foolproof solution i can come up with. 

I am not necessarily suggesting reserve manager collaboration. But essentially to put a mechanism in place that gives contributors a peace of mind. If there are other reserve with a higher balance having a similar rate, it means that the rate the manager trying to set is legitimate. So there is no need to go through the cumbersome process of getting permission from contributors. However, if you have a simpler foolproof mechanism than requiring explicit permission, it would make sense to use that mechanism itself for each reserve.

**Comment by yaronvel** [comment]
Can you please define more formally price manipulation?
Also by contributors, do you mean exchange users or reserve owners?

**Comment by GauthamN** [comment]
According to your whitepaper:

> One of the primary concerns is that a bad/unethical reserve manager may quote and
trade bad prices to him/herself to drain all coins from the reserve.

This is a valid problem in public reserve types. I was trying to come up with an efficient solution to this problem. The safest way to prevent price manipulation would be to restrict significant price changes below a threshold ratio. But it is not uncommon in crypto for sudden and significant price changes to happen naturally. One way is to add a requirement to get approval from reserve contributors when such as sudden price change is requested. But this alone would be highly inconvenient and cumbersome. 

Contributors as in 'Reserve Contributor' actor as defined in your whitepaper actors section.

**Comment by yaronvel** [comment]
Ok, I see what you mean now. Didn't realize you are talking about public reserves.
So yes, your proposal does make sense.
For now we start with private reserve. The governance models for public reserves would likely be another layer atop existing code. So your suggestion could fit there.

**Comment by GauthamN** [comment]
Thanks, Excited for the number of possibilities that can enhance the network. So rooting for modular contract philosophy.

**Comment by yaronvel** [comment]
public reserves are currently handled outside of kyber network. e.g., with melonport protocol
