### ISSUE TITLE
Missing deployment_tutorial branch

### ISSUE THREAD

**Issue by jamesdawsonWD** [KyberNetwork/smart-contracts#1049]
Hey guys, 

I have been following your tutorial at [](https://developer.kyber.network/docs/ReservesGuide/ ) - The deployment_tutorial branch doesn't seem to exist anymore. I am assuming master will work for deploying to ropsten? 

Not sure if this is the right place for this so feel free to close it, just thought I would let you know that the guide needs updated :)

**Comment by Anyhowclick** [comment]
Hello, you may be looking at a cached version of the developer portal. Not sure which reserve you are deploying, but here are the links:
https://developer.kyber.network/docs/Reserves-FedPriceReserve/
https://developer.kyber.network/docs/Reserves-AutomatedPriceReserve/
