### ISSUE TITLE
Determine best reserve for the trade

### ISSUE THREAD

**Issue by yaronvel** [KyberNetwork/smart-contracts#11]
1. Chose only 1 reserve.
2. If price is similar decide randomly according to `sha3(timestamp)`.
3. Implement similar price mechanism.
a. configurable epsilon - changes smaller than epsilon are negligable
b. go over all reserves and find cheapest price, and store it on array.
c. find all reserves with eplison from cheapest and store in an array
d. pick a reserve at random.

**Comment by ilanDoron** [comment]
@yaronvel 
I see you handled this. right?
