### ISSUE TITLE
'TransferAdminPending' event is passed with 2 different variables.

### ISSUE THREAD

**Issue by ldmtam** [KyberNetwork/smart-contracts#171]
Hi, when I read "PermissionGroups.sol", I saw that you defined an event and 2 transfer functions as following:  
```
event TransferAdminPending(address pendingAddress);  
function transferAdmin(address newAdmin) public onlyAdmin
function transferAdminQuickly(address newAdmin) public onlyAdmin
```
In "transferAdmin" function, you called that event with "pendingAdmin" param, which is address(0). But in "transferAdminQuickly" function, you again called that event with "newAdmin" param.  
  
Please explain why you call that event with 2 different variables. Thanks.

**Comment by yaronvel** [comment]
Looks like a real bug. Thank you for the report.
Although this bug is mainly cosmetic and not really covered by our bug bounty program, we would send you small reward if you share you Ethereum address here or in a private message.

**Comment by ldmtam** [comment]
Wow, thank you so much. Here is my ethereum address: 0x7aff18BAcC8a74CE0c3EAcF203179BdD125C2C43

**Comment by yaronvel** [comment]
Done. If you want to convert the KNC to ETH, you are welcomed to use our exchange :)
https://kyber.network
