### ISSUE TITLE
trade return 0x

### ISSUE THREAD

**Issue by sskeater** [KyberNetwork/smart-contracts#183]
When I call trade method, it's return error message as response below

HTML:
`	<body>
	    <script type="text/javascript" src="js/bignumber.js" ></script>
	    <script src="js/web3.js"></script>
	    <script src="json/abi.js"></script>
	    <script src="test/web3Mainnet.js"></script>
	</body>`

Request:

`let web3 = new Web3('wss://mainnet.infura.io/ws');
let privateKey = '*****************';
web3.eth.defaultAccount = web3.eth.accounts.privateKeyToAccount(privateKey).address;
let contract = new web3.eth.Contract(mainNetKyberAbi, mainNetKyberContractAddress);
contract.methods.trade(
    '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
    web3.eth.abi.encodeParameter('uint', new BigNumber(1 * Math.pow(10, 18))),
    '0xcec7f0df01a3cc5f9d41f08f2655066b80a093f0',
    web3.eth.defaultAccount,
    web3.eth.abi.encodeParameter('uint', new BigNumber(2).pow(255)),
    1,
    0).call();`

Response:
`{"jsonrpc":"2.0","id":1,"result":"0x"}`

However, it's worked on metamask with the code below:

`let contract = TruffleContract({
    abi:mainNetKyberAbi,
});
contract.setProvider(web3.currentProvider);
contract.at(mainNetKyberContractAddress).then(function(instance) {
    let b = instance.trade(
        '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
        new BigNumber(1 * Math.pow(10, 18)),
        '0xcec7f0df01a3cc5f9d41f08f2655066b80a093f0',
        web3.eth.defaultAccount,
        new BigNumber(2).pow(255),
        1,
        0
    );
    console.info(b)
});
`

**Comment by sskeater** [comment]
Thank for your answer.
I got another question:
`The method eth_sendTransaction does not exist/is not available`

my code is:
`contract.methods.trade(
    '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
    web3.eth.abi.encodeParameter('uint', new BigNumber(1 * Math.pow(10, 18))),
    '0xcec7f0df01a3cc5f9d41f08f2655066b80a093f0',
    web3.eth.defaultAccount,
    web3.eth.abi.encodeParameter('uint', new BigNumber(2).pow(255)),
    1,
    0).send({
        from:web3.eth.defaultAccount
    }).then(console.log);`

Is my "web3.js" version error? my "web3.js" version: 1.0.0-beta.34,

**Comment by yaronvel** [comment]
Version is ok probably. But maybe web3 is not connected to geth/parity or something?

**Comment by yaronvel** [comment]
I see you are using infura, but it cannot sign for you. Only send raw txs.

**Comment by sskeater** [comment]
@yaronvel 

This is the response:

`{"jsonrpc":"2.0","id":1,"method":"eth_gasPrice","params":[]}
{"jsonrpc":"2.0","id":1,"result":"0x77359400"}
{"jsonrpc":"2.0","id":2,"method":"eth_sendTransaction","params":[{"from":"0x4eaf770b82254b6fb914cdb55cb15cc091073c0a","data":"0xcb3c28c7000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000cec7f0df01a3cc5f9d41f08f2655066b80a093f00000000000000000000000004eaf770b82254b6fb914cdb55cb15cc091073c0a800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000","gasPrice":"0x77359400","to":"0x964f35fae36d75b1e72770e244f6595b68508cf5"}]}
{"jsonrpc":"2.0","id":2,"error":{"code":-32601,"message":"The method eth_sendTransaction does not exist/is not available"}}`
