### ISSUE TITLE
Transaction Error. Exception thrown in contract code

### ISSUE THREAD

**Issue by sskeater** [KyberNetwork/smart-contracts#185]
Hi, @yaronvel 

When I call trade method with metamask wallet, metamask told me "Transaction Error. Exception thrown in contract code". But no more tips showed to me.

code:
`let contract = TruffleContract({
    abi: mainNetKyberAbi,
});
contract.setProvider(web3.currentProvider);
contract.at(mainNetKyberContractAddress).then(function(instance) {
    instance.getExpectedRate('0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', '0x86Fa049857E0209aa7D9e616F7eb3b3B78ECfdb0', 0).then(function(a, b) {
        instance.trade(
            '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
            new BigNumber(1 * Math.pow(10, 18)),
            '0xcec7f0df01a3cc5f9d41f08f2655066b80a093f0',
            web3.eth.defaultAccount,
            new BigNumber(2).pow(255),
            new BigNumber(65559682300000),
            0, {
                from: web3.eth.defaultAccount,
                value: new BigNumber(0.001 * Math.pow(10, 18)),
            }
        ).then(function(b) {
            console.info(b)
        });
    });
});`

txid:0x2c0ac368f5e9d5215f62fa6d877114479413cf5e89ff958f8da8702df5aa0f50

**Comment by yaronvel** [comment]
You set 'srcAmount' to 1 eth, but value to 0.001 eth. They must be the same.
