### ISSUE TITLE
It's returned 405 when I send method trade

### ISSUE THREAD

**Issue by sskeater** [KyberNetwork/smart-contracts#189]
@yaronvel 

It's returned 405 when I send method trade, could you help me?

`
const eos = '0xd3c64BbA75859Eb808ACE6F2A6048ecdb2d70817';
const eth = '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee';
const web3 = new Web3('https://ropsten.infura.io/DtzEYY0Km2BA3YwyJcBG');
// ...
contract.methods.trade(
    eos,
    new BigNumber(0.001 * Math.pow(10, 18)),
    eth,
    web3.eth.defaultAccount,
    new BigNumber(2).pow(255),
    1,
    0
).send({
        from: web3.eth.defaultAccount,
        value: new BigNumber(0.001 * Math.pow(10, 18))
    },
    function(result) {
        console.info('Send result: ')
        console.info(result)
    }).then(function(send) {
    console.info('Trade: ')
    console.info(send);
});`

**Comment by yaronvel** [comment]
Did you gave EOS allowance to the contract before the tx? You need to.

**Comment by sskeater** [comment]
@yaronvel 
When I call approve method, it also return 405, like this:

eosContract.methods.approve(eos, new BigNumber(1 * Math.pow(10, 18))).send(
    {
        from:web3.eth.defaultAccount
    }
).then(function(approve){
    console.info('Approve: ')
    console.info(approve)
});

**Comment by yaronvel** [comment]
oh, you cannot use `send` with infura as it cannot sign in behalf of you.
Either use local parity/geth node (and unlock it), or sign your tx local and use infura to send raw txs.

**Comment by sskeater** [comment]
@yaronvel 
Thanks for your help, I had implemented as this:

/** approve */
let approve = eosContract.methods.approve(ropstenKyberAddress, new BigNumber(0.1 * Math.pow(10, 18)));
let approveData = approve.encodeABI();
web3.eth.getGasPrice().then(function(gp) {
    approve.estimateGas().then(function(g) {
        web3.eth.accounts.signTransaction({
            to: eos,
            gas: g,
            gasPrice: gp,
            data: approveData
        }, userPrivakey).then(function(sign) {
            web3.eth.sendSignedTransaction(sign.rawTransaction).then(function(result) {
                console.info(result)
            })
        });
    })
});

/** transfer eos to eth*/
let b = contract.methods.trade(
    eos,
    new BigNumber(0.1 * Math.pow(10, 18)),
    eth,
    web3.eth.defaultAccount,
    new BigNumber(2).pow(255),
    1,
    0
)
web3.eth.getGasPrice().then(function(gp){
    b.estimateGas().then(function(g){
        web3.eth.accounts.signTransaction({
            from: web3.eth.defaultAccount,
            to:ropstenKyberAddress,
            gas: g,
            gasPrice: gp,
            value: 0,
            data:b.encodeABI()
        }, userPrivakey).then(function(sign){
            let msg = web3.eth.accounts.recoverTransaction(sign.rawTransaction)
            console.info(msg)
            web3.eth.sendSignedTransaction(sign.rawTransaction).then(function(result){
                console.info(result)
            })
        })
    })
})
