### ISSUE TITLE
 The method "estimateGas " returned "gas required exceeds allowance or always failing transaction"

### ISSUE THREAD

**Issue by sskeater** [KyberNetwork/smart-contracts#191]
Hi @yaronvel 
I got a new question when I'm try to transfer ETH to EOS. The method "estimateGas " returned "gas required exceeds allowance or always failing transaction";
Do you know how to fix it? Thanks.

let b = contract.methods.trade(
    eth,
    new BigNumber(0.01 * Math.pow(10, 18)),
    eos,
    web3.eth.defaultAccount,
    new BigNumber(2).pow(255),
    1,
    0
);
b.estimateGas() // ERROR

**Comment by yaronvel** [comment]
This indicates tx suppose to fail. The reason is you have to set msg.value to 0.01 ETH.
