### ISSUE TITLE
README is inaccurate. No getRate function

### ISSUE THREAD

**Issue by elie222** [KyberNetwork/smart-contracts#192]
The README is inaccurate. There is no `getRate` function anymore. This may be a remnant of old code. There is `getExpectedRate` and `findBestRate` in KyberNetwork contract. ConversionRates contract has a `getRate`.

**Comment by yaronvel** [comment]
Where do you read it?
This is the official integration doc https://github.com/KyberNetwork/smart-contracts/blob/master/integration.md

**Comment by elie222** [comment]
The main readme of the repo. (Also would be great if we could connect on
LinkedIn. Sent you a connect not long ago).

**Comment by elie222** [comment]
This is what I was referring to:
https://github.com/KyberNetwork/smart-contracts#getrate-function

**Comment by ilanDoron** [comment]
The readme was updated.
