### ISSUE TITLE
negative qty

### ISSUE THREAD

**Issue by rotcivegaf** [KyberNetwork/smart-contracts#210]
https://github.com/KyberNetwork/smart-contracts/blob/d2e418ccc4b1942847b751b369bf51d8fc290671/test/kyberReserve.js#L64

why put negative qty, if you have a unit you can't haves negatives

**Comment by yaronvel** [comment]
Units can be negative.
But imbalance can be negative (if it is imbalanced towards sell)

**Comment by ilanDoron** [comment]
should remove all negative quantity x values.
quantity can't be negative.

**Comment by manhlx3006** [comment]
Already changed in `kyberReserve.js`, `kyberNetwork.js`, `kyberNetworkProxy.js`, `expectedRate.js` with enhanced step func PR: https://github.com/KyberNetwork/smart-contracts/pull/422

**Comment by ilanDoron** [comment]
great
closing.
