### ISSUE TITLE
token to token trade. report number of ethers in trade event.

### ISSUE THREAD

**Issue by ilanDoron** [KyberNetwork/smart-contracts#230]
currently trade include src amount and dest amount.
for token to token trade, this doesn't include Ether. so add Ether amount to this event.

**Comment by yaronvel** [comment]
not to trade event. it must be backwards compatible.
Need an event for `doReserveTrade` in network contract.

**Comment by ilanDoron** [comment]
but do reserve trade happens twice....
we want two events?

**Comment by yaronvel** [comment]
in any case, we dont want to change main event in network proxy

**Comment by ilanDoron** [comment]
added to event KyberTrade in KyberNetwork.sol
delivered to master in #373
