### ISSUE TITLE
dev_testnet.md is outdated

### ISSUE THREAD

**Issue by WyseNynja** [KyberNetwork/smart-contracts#392]
Where did the `./test/ethdistribution.js` and `./test/deployment.js` scripts go? Has something replaced them?

I see a few different scripts in `web3deployment`, but am not sure what I should be using to deploy your contracts to a local ganache instance for testing.

**Comment by WyseNynja** [comment]
Aha. It looks like they moved to https://github.com/KyberNetwork/smart-contracts/tree/master/scripts

**Comment by yaronvel** [comment]
yes, and the official documentation is not at developer.kyber.network
