### ISSUE TITLE
Permission base contract

### ISSUE THREAD

**Issue by yaronvel** [KyberNetwork/smart-contracts#4]
Three levels of permissions:
1. Admin - can give permissions to others. Only 1 admin.
2. Operator - for example, set prices in reserve manager. Can have multiple operators.
3. Alerter - for example, stop trade in token if he thinks something is wrong. Can have multiple alerter.

Requirements:
1. Admin is transferable. With `acceptOwnership` function.
2. Modifier for `onlyAdmin`, `onlyOperator` and `onlyAlerter`.
3. `getOperators` and `getAlerters` functions. Implement with naive array.

**Comment by ilanDoron** [comment]
should we consider optional description strings per alerters and operators?

**Comment by yaronvel** [comment]
@ilanDoron we should also make a pure interface for this. To avoid multiple inheritance issues.
I.e., only the main contract should inherit from this contract, and the rest should inherent only from the interface.

**Comment by ilanDoron** [comment]
what do you consider the main contract?
