### ISSUE TITLE
what logs to watch for price changes?

### ISSUE THREAD

**Issue by WyseNynja** [KyberNetwork/smart-contracts#400]
I'm looking at these contracts for the first time and I'm not seeing any events emitted when a reserve changes the price for a token. Am I missing something?

I'm wanting to write some simple code that builds a dashboard using web3 to get the prices for all tokens available on Kyber. Then I want it to subscribe to something so that any time a price on any reserve changes or a new reserve is added, the price is recalculated. Which events should I subscribe to?

**Comment by yaronvel** [comment]
No events. One reason is to save gas. Another reason is that price delends also in other contracts and price change might be triggered indirectly

**Comment by ilanDoron** [comment]
Notice price can't be directly figured out.

Kyber has few reserve types.
Automatic market maker reserve. the price changes according to buy / sell
by the users.

on price fed reserve there is order book like behavior. there are steps for
different quantities. so larger quantity will result in higher price.
u best read expected price for your quantity by off chain call.
