### ISSUE TITLE
KyberNetworkProxyInterface is missing trade()

### ISSUE THREAD

**Issue by nance2uiuc** [KyberNetwork/smart-contracts#406]
As it is written currently, swapEtherToTokenWithChange() will error on compilation, because KyberNetworkProxyInterface is missing trade(), even though it is implemented in KyberNetworkProxy. 

To fix this, you will have to edit KyberNetworkProxyInterface.sol yourself as follows: 

add `function trade(ERC20 src,uint srcAmount,ERC20 dest,address destAddress,
    	uint maxDestAmount,uint minConversionRate,address walletId) public payable returns(uint);`

**Comment by ilanDoron** [comment]
swapEtherToTokenWithChange() in which contract?

in KyberNetworkProxy the formal API is tradeWithHint() and not trade.
