### ISSUE TITLE
KyberNetworkProxyInterface is missing trade()

### ISSUE THREAD

**Issue by nance2uiuc** [KyberNetwork/smart-contracts#407]
As it is written currently, swapEtherToTokenWithChange() will error on compilation, because KyberNetworkProxyInterface is missing trade(), even though it is implemented in KyberNetworkProxy. 

To fix this, you will have to edit KyberNetworkProxyInterface.sol yourself as follows: 
 ```
function trade(ERC20 src,uint srcAmount,ERC20 dest,address destAddress,
    	uint maxDestAmount,uint minConversionRate,address walletId) public payable returns(uint);
```

**Comment by yaronvel** [comment]
I am not farmiliar with the function swap ether to token with change. Please explain what you mean

**Comment by nance2uiuc** [comment]
Hi yaronvel,

I am following the dApp integration guide here: https://developer.kyber.network/docs/DappsGuide/

Is this still current?

**Comment by yaronvel** [comment]
it seems that the guide is using `KyberNetworkProxy.sol` directly and not the interface. Which is not optimal. We will contact them to fix it.
In the mean time, either import the `KyberNetworkProxy.sol` or use `tradeWithHint`. If you pass empty hint, you will get the same effect as `trade`.
To have an empty hint `h`, just do:

```
bytes h = new bytes;
```
and pass `h` as hint.

**Comment by nance2uiuc** [comment]
Thanks, using the newer guide now.
