### ISSUE TITLE
Error: Failed to check for transaction receipt

### ISSUE THREAD

**Issue by rogerdsx** [KyberNetwork/smart-contracts#411]
While deploying the contracts:

**Expected behavior:**

    }
  },
  "reserve": "RESERVE ADDRESS",
  "pricing": "PRICING ADDRESS",
  "network": "NETWORK ADDRESS"
}
liquidityReserve_deployment.json write
Done

**Actual Behavior:**

    }
  },
  "reserve": "RESERVE ADDRESS",
  "pricing": "PRICING ADDRESS",
  "network": "NETWORK ADDRESS"
}
liquidityReserve_deployment.json write
Done
Error: Failed to check for transaction receipt:
{}
    at Object._fireError (C:\Users\tyler\OneDrive - DataStreamX\DSX_Backup 2\190717_Quadrant-Kyber-Integration\mainnet\node_modules\web3-utils\src\index.js:56:17)
    at C:\Users\tyler\OneDrive - DataStreamX\DSX_Backup 2\190717_Quadrant-Kyber-Integration\mainnet\node_modules\web3-core-method\src\index.js:260:23
    at <anonymous> Promise {
  <rejected> Error: Failed to check for transaction receipt:
{}
    at Object._fireError (C:\Users\tyler\OneDrive - DataStreamX\DSX_Backup 2\190717_Quadrant-Kyber-Integration\mainnet\node_modules\web3-utils\src\index.js:56:17)
    at C:\Users\tyler\OneDrive - DataStreamX\DSX_Backup 2\190717_Quadrant-Kyber-Integration\mainnet\node_modules\web3-core-method\src\index.js:260:23
    at <anonymous>,
  _events: undefined,
  emit: [Function: emit],
  on: [Function: on],
  once: [Function: once],
  off: [Function: removeListener],
  listeners: [Function: listeners],
  addListener: [Function: on],
  removeListener: [Function: removeListener],
  removeAllListeners: [Function: removeAllListeners] }
Error: Failed to check for transaction receipt:
{}
    at Object._fireError (C:\Users\tyler\OneDrive - DataStreamX\DSX_Backup 2\190717_Quadrant-Kyber-Integration\mainnet\node_modules\web3-utils\src\index.js:56:17)
    at C:\Users\tyler\OneDrive - DataStreamX\DSX_Backup 2\190717_Quadrant-Kyber-Integration\mainnet\node_modules\web3-core-method\src\index.js:260:23
    at <anonymous> Promise {
  <rejected> Error: Failed to check for transaction receipt:
{}
    at Object._fireError (C:\Users\tyler\OneDrive - DataStreamX\DSX_Backup 2\190717_Quadrant-Kyber-Integration\mainnet\node_modules\web3-utils\src\index.js:56:17)
    at C:\Users\tyler\OneDrive - DataStreamX\DSX_Backup 2\190717_Quadrant-Kyber-Integration\mainnet\node_modules\web3-core-method\src\index.js:260:23
    at <anonymous>,
  _events: undefined,
  emit: [Function: emit],
  on: [Function: on],
  once: [Function: once],
  off: [Function: removeListener],
  listeners: [Function: listeners],
  addListener: [Function: on],
  removeListener: [Function: removeListener],
  removeAllListeners: [Function: removeAllListeners] }

node version v8.11.2

**Comment by ilanDoron** [comment]
many times failure to get Tx receipt is due to slow mining. many times when gas price is low and mining takes time.

are the contracts actually deployed?
was gas price relatively low?

**Comment by rogerdsx** [comment]
Hey @ilanDoron ! Found that the contracts are deployed. And I echo you. I believe I got this error due to slow mining.
