### ISSUE TITLE
Link to Smartcontract Integration Points to Nowhere

### ISSUE THREAD

**Issue by ejtejada** [KyberNetwork/smart-contracts#412]
Greetings!
I am studying how I might integrate your protocol with a wallet, but your link in this repo's readme:
https://github.com/KyberNetwork/smart-contracts/blob/master/integration.md

Results in a 404 error. 

I  see that this file is referenced in several other resolved issues, but I can find no such integration.md file in this repository.

**Comment by ilanDoron** [comment]
Please use docs here
https://developer.kyber.network/docs/Start/

**Comment by ejtejada** [comment]
Hello again.
I appreciate the correct link! However, I would also appreciate if this project's readme no longer had that deadlink, but instead included the link to https://developer.kyber.network/docs/Start/
as well?

**Comment by ilanDoron** [comment]
Can u check again please.

**Comment by ejtejada** [comment]
Hello again, the link on this projec's readme has not changed, and is still the deadlink:
https://github.com/KyberNetwork/smart-contracts/blob/master/integration.md
Please change it to:
https://developer.kyber.network/docs/Start/
?

**Comment by ejtejada** [comment]
@Anyhowclick Thanks for the pull request. Closed.
