### ISSUE TITLE
Eth 2 DAI reserve enhancement 

### ISSUE THREAD

**Issue by ilanDoron** [KyberNetwork/smart-contracts#435]
For better using Eth2DAI liquidity source.
have algorithm to define number of takes and traverses on the order book.

**Algorithm**
Algorithm will have :
max number of takes
max number of traverse.
min size of order to take

Max_number_of_takes = base_takes + take_factor * trade_size; capped by constant max
Max_number_of_traverse = base_traverse + traverse_factor * trade_size; capped by constant max.
Min_take_size = base_take_size + min_take_factor * trade size.

The base and factor parameters will be adopted to eth Src amount. 
If trade src amount is in token:
- read first bid and ask. 
- verify ask > bid.
- find median.
- use median to convert amount to Eth
calculate  Max_number_of_takes, Max_number_of_traverse, Min_take_size. 
convert min_take_size to token value.
return values.

**values storage**
above algorithm values should be configurable.
to avoid extra sload
should be squeezed into a few uint values.
uint32 should be big enough for all values.
since decimal values are required.
amount will be stored in BFS (basic factor steps) of size 1 / 100000
so if user wants to set 4.31961 he should set 431961
 
**internal inventory usage**
internal inventory will be used sometimes to fill trades.
when internal inventory is used. 
the price can be taken from few first levels. or from one. should decide.
few levels is gas expensive. but first level might not reflect correct price if trade amount much bigger then this offer.

for checking if there is "bad spread" check min spread > minimum expected value.

**min amount to use reserve**.
a min amount value will help deciding if reserve should be used to trade. for small trades this reserve is too expensive. and rather not use it at all.
Min trade amount will be saved in eth.
if srcAmount token use same as above to find median. convert min amount to token and decide if to return rate.

**Comment by ilanDoron** [comment]
yes.
I mean avoid one read in function shouldUseInternalInventory.
there one ask offer and one bid offer are read. but we actually already read one of them.

**Comment by ilanDoron** [comment]
@manhlx3006 
following a talk with Spyros, One more comment.

The values for the algorithm are defined in DAI values.
should be converted to eth when trade is Eth 2 DAI and srcQty is Eth.
for this conversion we use first offer in the order book.

but for using this first offer. we should check spread is OK
same as we later do for internal inventory...
so it seems the spread check should move to early stage of the call. so same spread check can be used in a few places...

**Comment by ilanDoron** [comment]
internal inventory fee assumptions.
the internal inventory logic is as follows.

assume min spread is 0.6%
and we give premium (better rate) of 0.05%

so adding both it creates min spread for internal which is 0.5%
and this assumes that extra 0.25% fee will be taken.
So extra 0.25% from each side takes it to median price.

so actually idea is that minSpreadBps >= (feeBps + premiumBps) * 2

in our case its (25 + 5) * 2 = 60

which is the current numbers.
so if the spread is minimum. we don't loose any money. our gains will be used to pay fee

should add test to block minBps that is too small.

**Comment by manhlx3006** [comment]
The first implementation can be found here:
Contract: https://etherscan.io/address/0x31180c2e1a962006ad17f99c94646d5eaac62957
First swap ETH -> DAI: https://etherscan.io/tx/0xc341073b329e7ff0ab580724de455b525ce533323164ceab9451056249f1e468
First swap DAI -> ETH: https://etherscan.io/tx/0x91e8e86b35cd75d3c040be3220ebcdd16758335ca32476256d8961acca744f29
Source code is in my secret gist, will public later

**Comment by ilanDoron** [comment]
great.
what are our next steps?
did you start with regression?

**Comment by manhlx3006** [comment]
I just did some tests about getting rates, do some trades, play around with some configs number for max traverse, max takes and min order size to take.
We should have some proposal configs number and do regression.
For regression, can you help to list down some things that we should test? I will follow some of your search data.

**Comment by manhlx3006** [comment]
PR with source codes + tests here: https://github.com/KyberNetwork/smart-contracts/pull/449/files

**Comment by ilanDoron** [comment]
deployed to production.
