### ISSUE TITLE
Use Checksummed Ether Address instead of 00 prefix 

### ISSUE THREAD

**Issue by Anyhowclick** [KyberNetwork/smart-contracts#436]
@LefterisJP [suggested that we use the checksummed ETH address instead of the `0x00eee...e ` address](https://github.com/KyberNetwork/developer-portal/pull/84#issuecomment-530694691_):

> Apparently solidity treats hexadecimal literals that have a `00` prefix and are between 39-41 
> bytes in a special way and does not need to checksum them.
> 
> And since you cast it to `ERC20` in the code the first two 00 are dropped in the code.
> 
> To avoid confusion like this perhaps it would have made sense to give the check-summed 
> constant as the magic constant for Ether in the contract?

**Comment by ilanDoron** [comment]
yes.
we should.
in which contract?
please add relevant label. or create one if required.

**Comment by ilanDoron** [comment]
done on new utils contract
