### ISSUE TITLE
Avoid decimals() call per call to handleFees on feeBurner

### ISSUE THREAD

**Issue by ilanDoron** [KyberNetwork/smart-contracts#437]
Since setDecimals isn't called. decimals are queried for KNC per call to handleFees.
Can see it here for example:

https://bloxy.info/tx/0x1c80dc74da5a81fe4b5dc797fbfbc0820d63d4f687c1be2c18b9f33b12a6b51e

actually can use constant for KNC decimals.
since its not likely to be changed.
so can use some COMMON_DECIMALS for required calls.

motivation is to save gas.

**Comment by manhlx3006** [comment]
It seems we already changed in our latest develop branch, however it has an issue:
```uint kncAmount = tradeWeiAmount * kncPerETHRate;```
while it should be
 ```uint kncAmount = tradeWeiAmount * kncPerETHRate / PRECISION;```

**Comment by manhlx3006** [comment]
Added PR for development branch here: https://github.com/KyberNetwork/smart-contracts/pull/468

**Comment by ilanDoron** [comment]
Merged to master and deployed.
