### ISSUE TITLE
Reduce getDecimals call in findBestRateTokenToToken

### ISSUE THREAD

**Issue by manhlx3006** [KyberNetwork/smart-contracts#464]
in findBestRateTokenToToken we have:
```
(result.reserve1, result.rateSrcToEth) = searchBestRate(src, ETH_TOKEN_ADDRESS, srcAmount);
result.weiAmount = calcDestAmount(src, ETH_TOKEN_ADDRESS, srcAmount, result.rateSrcToEth);

(result.reserve2, result.rateEthToDest) = searchBestRate(ETH_TOKEN_ADDRESS, dest, result.weiAmount);
result.destAmount = calcDestAmount(ETH_TOKEN_ADDRESS, dest, result.weiAmount, result.rateEthToDest);

result.rate = calcRateFromQty(srcAmount, result.destAmount, getDecimals(src), getDecimals(dest));

```

in ```calcDestAmount``` and ```calcRateFromQty``` we need to get decimals for src/dest token to compute value.

To reduce number of ```getDecimals``` calls, we can get the decimals of src and dest token, and pass to ```calcDestAmount``` and ```calcRateFromQty```

Propose:

```
uint srcDecimals = getDecimals(src);
uint destDecimals = getDecimals(dest);

(result.reserve1, result.rateSrcToEth) = searchBestRate(src, ETH_TOKEN_ADDRESS, srcAmount);
result.weiAmount = calcDestAmount(srcDecimals, ETH_DECIMALS, srcAmount, result.rateSrcToEth);

(result.reserve2, result.rateEthToDest) = searchBestRate(ETH_TOKEN_ADDRESS, dest, result.weiAmount);
result.destAmount = calcDestAmount(ETH_DECIMALS, destDecimals, result.weiAmount, result.rateEthToDest);

result.rate = calcRateFromQty(srcAmount, result.destAmount, srcDecimals, destDecimals);
```

After running tests, this changes reduce around 2000 gas and could be more when applying Istanbul.

PR created: https://github.com/KyberNetwork/smart-contracts/pull/467

**Comment by ilanDoron** [comment]
So this is a nice save and code changes are minimal and easy to self audit.
For Istanbul gas saving should grow to 3000+ per trade.

**Comment by manhlx3006** [comment]
I updated PR to `development`: https://github.com/KyberNetwork/smart-contracts/pull/467

**Comment by ilanDoron** [comment]
merged with #467

**Comment by ilanDoron** [comment]
my mistake.
should be closed when merged to master.

**Comment by ilanDoron** [comment]
Merged to master and deployed to production
