### ISSUE TITLE
Failing KNP tests on ganache Istanbul version

### ISSUE THREAD

**Issue by Anyhowclick** [KyberNetwork/smart-contracts#478]
On the `clicky/ganacheIstanbul` branch, running `./tst.sh -f "./test/kyberNetworkProxy.js" ` gets all 76 tests passing.

However, running `./tst.sh -f "./test/kyberNetworkProxy.js -k "istanbul"` results in 2 failing tests.
<img width="1213" alt="FailingTests" src="https://user-images.githubusercontent.com/12406924/68557846-13037d00-0472-11ea-8589-aa359bb51944.png">

It might seem that the problem lies with the KyberNetwork contract, but all tests pass when running `./tst.sh -f "./test/kyberNetwork.js -k "istanbul"`, which includes the same 2 tests that fail in the KNP test file.
https://github.com/KyberNetwork/smart-contracts/blob/clicky/ganacheIstanbul/test/kyberNetwork.js#L769-L812
https://github.com/KyberNetwork/smart-contracts/blob/clicky/ganacheIstanbul/test/kyberNetwork.js#L1979-L2002

This SHOULD mean that the problem lies in the proxy contract.

To get a better sense of why the 2 tests fail, I wanted to use Builder's solidity stack trace. To do that, I rewrote the network proxy, network contracts and interfaces to V5, with error messages for require and revert statements, which can be shown by Buidler (yay!):
https://github.com/Anyhowclick/smart-contracts/tree/istanbulError/contractsV5

It also meant rewriting to test file to web3 1.x in order to fully make use of the solidity stack trace. Due to time constraints, I rewrote up to the first failing test:
https://github.com/Anyhowclick/smart-contracts/blob/istanbulError/test/knpV5.js

Cloning the above repo and running `npx buidler test -f "./test/knpV5.js"` yields the following traces (ignoring the other test failures due to BN and syntax issues):
<img width="902" alt="FailingTest1" src="https://user-images.githubusercontent.com/12406924/68559564-6bd61400-0478-11ea-890e-91c3676584ee.png">
<img width="799" alt="FailingTest2" src="https://user-images.githubusercontent.com/12406924/68559582-75f81280-0478-11ea-8405-824b868d99f6.png">

The first failing test seems to have failed when excess source tokens are being returned to the user. It doesn't seem to have failed at any require statement. Otherwise, the error message would be displayed, like the one below:
<img width="800" alt="FailingTest3" src="https://user-images.githubusercontent.com/12406924/68560250-3ed73080-047b-11ea-89ce-a40eb9bbb6b2.png">

Tried commenting out some contract code, but I can't figure out what's wrong =/

**Comment by ilanDoron** [comment]
Created a simple scenario that shows the problem is in Istanbul code.
for first failing test.
with low max dest amount
See details here:
https://github.com/ilanDoron/showGanacheBug

**Comment by ilanDoron** [comment]
fixed.
