### ISSUE TITLE
Withdrawable base contract

### ISSUE THREAD

**Issue by yaronvel** [KyberNetwork/smart-contracts#5]
Withdrawable inherent from permission.
Only admin can call it.  
Should be able to withdraw both ether and token.
Something similar to [this](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/ownership/CanReclaimToken.sol#L22) and [this](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/ownership/HasNoEther.sol#L37).

**Comment by ilanDoron** [comment]
functions. 
withdrawToken
withDrawEther
