### ISSUE TITLE
reduce gas in deployment of contract permissionGroups

### ISSUE THREAD

**Issue by ilanDoron** [KyberNetwork/smart-contracts#50]
try set permissions all in function. test affect on deployment cost.

**Comment by yaronvel** [comment]
what? I cannot understand this sentence.

**Comment by ilanDoron** [comment]
now u can?

**Comment by yaronvel** [comment]
save gas in deployment?

**Comment by ilanDoron** [comment]
now better?

**Comment by yaronvel** [comment]
yes, just for the record. the pricing contract is reaching 4.7M (ropsten) gas limit, and we need to reduce code size for it.

**Comment by ilanDoron** [comment]
Well
Will be happy to work on that...

בתאריך 4 בינו 2018 15:37,‏ "yaronvel" <notifications@github.com> כתב:

**Comment by yaronvel** [comment]
Closing as we decided to use kovan instead.
