### ISSUE TITLE
Upgradable get expected price function (only for UI)

### ISSUE THREAD

**Issue by yaronvel** [KyberNetwork/smart-contracts#7]
support `getExpectedRate( ERC20 srcToken, ERC20 destToken, uint srcQty, address userAddres )`.
`KyberNetwork` keeps a pointer to it. Upgradable by admin.

**Comment by ilanDoron** [comment]
get expected rate will be a seperate contract.
1. interface ExpectedRateInterface that exposes 
- getExpectedRate
- `setKyberNetwork` to set the contract address by admin.
- 'setQuantityFactor'
2. initial ExpectedRate is Withdrawble, is PermisionGroup, is ExpectedRateInterface, KyberConstants
3. define first algorithm. getExpectedRate
bestRate = findBestRate (src, dst, quantity)
slippageRate = findBestRate(src, dst, quantity * quantityFactor) - this is to take 
return (uint bestRate, uint slippageRate)
