### ISSUE TITLE
coverage tests

### ISSUE THREAD

**Issue by ilanDoron** [KyberNetwork/smart-contracts#73]
add tests for new code:
## volume imbalance recorder 
(over flow checks)
## converstionRates
new getters

**Comment by ilanDoron** [comment]
add tests for get src qty where output is near 0.
now should make sure its rounded up...

**Comment by ilanDoron** [comment]
all above done.
remaining coverage is see why max rate not reached in coverage.

**Comment by yaronvel** [comment]
@ilanDoron what is the status?

**Comment by ilanDoron** [comment]
Katalyst has full coverage
