### ISSUE TITLE
max per block and max total imbalance should be presented in ether (wei)

### ISSUE THREAD

**Issue by ilanDoron** [KyberNetwork/smart-contracts#82]
currently imbalance recorder operates with twei / token currency.
it would be more "readable" if values presented in ether (wei).
so change the whole logic to ether - keep imbalance in twei. set max in twei etc...

**Comment by ilanDoron** [comment]
question:
spyros
if token value drops big - lets say 30% and ether doesn't 
will we enlarge our reserve?
will lower our max imbalance?
because if its in ether - we should compensate on dramatic rate changes eth->token...

**Comment by yaronvel** [comment]
@ilanDoron please tag as 1.1 feature.

**Comment by aenaus** [comment]
>question:
spyros
if token value drops big - lets say 30% and ether doesn't
will we enlarge our reserve?
will lower our max imbalance?

This goes the same for eth/token rise or drop, regardless if we use  twei or wei.
We will update the twei numbers more often than the wei, so being able to set them in wei, makes it easier.

**Comment by yaronvel** [comment]
It will be a security threat to have that.
