### ISSUE TITLE
Gas Limit attack on removeAlerter and removeOperator

### ISSUE THREAD

**Issue by edeirme** [KyberNetwork/smart-contracts#92]
The functions `removeOperator` and `removeAlerter` of the `PermissionGroups.sol` contract are subject to a Gas Limit attack. 

Every action of a smart contract consumes gas. In case gas runs out, the contract will stop processing the transaction and the transaction will fail.

Both functions attempt to loop over the `operatorsGroup` and `alertersGroup` respectively without having a way to control the max number of iterations. 

In case those arrays are very large the `for` loop will consume all the gas and the transaction will fail.

Currently, there is no limit on the number of operators or alerters that can be added to the contract.

The impact of this issue is that in case a very big number of alerters or operators are added to the relevant arrays, the functions `removeOperator` or `removeAlerter` will become dysfunctional, being able to remove only alerters or operators being at the beginning of the `operatorsGroup` and `alertersGroup` arrays or at least before the transaction runs out of gas.

As a solution to this issue, the introduction of a limit to the number of operators or alerters is advised. 

Vulnerable snippet

```  
    for (uint i = 0; i < operatorsGroup.length; ++i) {
       if (operatorsGroup[i] == operator) {
                operatorsGroup[i] = operatorsGroup[operatorsGroup.length - 1];
                operatorsGroup.length -= 1;
                OperatorAdded(operator, false);
                break;
            }
        }

```
     
```
        for (uint i = 0; i < alertersGroup.length; ++i) {
            if (alertersGroup[i] == alerter) {
                alertersGroup[i] = alertersGroup[alertersGroup.length - 1];
                alertersGroup.length--;
                AlerterAdded(alerter, false);
                break;
            }
        }
```

**Comment by yaronvel** [comment]
Thanks. We are aware of this issue. However, since only admin can add them we do not consider it as an attack.
A bound is in order just to prevent non-tech admin from doing stupid things. However, the bound might be different to every application. so we are not in a rush to decide on it.

In practice, we do not plan over 10 of each. so it is fine.

**Comment by edeirme** [comment]
It is indeed an action that can be taken only by admin users, making the likelihood of this attack much less possible. 

The bound you are referring to is it application based or smart contract based? I haven't found any reference of the `PermissionGroups.sol` vulnerable functions in the rest of the smart contract of this branch.

Assuming an application-based bound will be in place, even though it guarantees that non-tech admins won't be able to trigger the vulnerability (considering that there is no bug or security vulnerability in the application) it does not guarantee that these functions cannot be called directly. 

There are two cases that the latter condition can be triggered. The first one is by considering the admin as a threat actor and the second one is that in the near future an update is made in the application code and either ignores the set 'bound' or increases it an excessively high amount.

Even though considering the admin as a threat actor is usually a weak statement, due to the existence of the `transferAdmin()` function, in this case, the malicious admin could take the role of a saboteur. Silently increasing the amount of Alerters and Operators till the gas limit vulnerability can be triggered.

The second case would be the result of negligence or for example the creation of a widget by developers, to make their job easier.

In either case, I trust that you have the best intentions and that a bound will be set in place. Nonetheless, I would recommend adding an upper limit in order to avoid this unwanted behavior.

**Comment by yaronvel** [comment]
If admin is a threat, he could just not delete operators. he does not need to attack the contract to do that.
For non-tech admin I agree. thing is that we still don't want to hard-code our bound.
We cannot think of a scenario of even 50 accounts being operators or alerters. But we want to be sure after several months.

The real bound is likely in the order of 1000s, so it will be very hard to make such mistake accidentally.

By the way, if you look at conversion rate contract. you will see an array of step functions there.
It is the same issue, only there operator can make an attack.
Still, we are not ready to commit on  a bound to the array size yet.
Also you will see we loop on all reserves, which will also fail if a lot of reserves are added.
But we know that in the next 1-2 months we will have only 1-3 reserves.

The contracts are designed to be upgradable.
Including KyberNetwork.sol which kybernetwork.eth ENS dictates the latest deployment.
We are aware of these issues, just that setting actual bound would require either accurate gas profiling or just see how many alerters and operators we will really need (and multiply it by 10 even).
Exact profiling is also problematic as gas limits can change (also go down).

Anyway, thanks for the comment, it was already in our todo list.

**Comment by edeirme** [comment]
That is correct, considering the admin as a threat actor, as I stated in the above comment, is a weak statement.

Indeed the number of operators and alerters would have to be in the order of 1000s in order to trigger this issue.

I appreciate taking the time to go over this issue. I'll cross out of my list the related issue on the conversion rate contract.

**Comment by yaronvel** [comment]
Please also note that in the event of the mistake admin can simply delete the first opertors and make the array smaller (and add them later).
In any case, this issue was fixed at this [commit](https://github.com/KyberNetwork/smart-contracts/commit/e4f7574006dabe2f133dac3646eed49f6636d05f).

**Comment by edeirme** [comment]
Hi yaronvel, 

Sorry for digging up this issue but I just noticed that you actually fixed the issue I mentioned. Since I reported a valid issue that was later fixed by your team does it mean that it qualifies for Kyber Network's bug bounty program?

Thanks

**Comment by yaronvel** [comment]
Hi.
1. One of our auditor already reported this issue before you did, and in any case we were aware of it before your report.
2. The bug bounty scope currently only covers bugs that put user and reserve funds at risk.

Hence, at the moment it does not qualify. However, if over time our bounty budget is not depleted we will consider it.
